//
//  SettingsView.swift
//  FaithBuilderApp
//
//  Created by Trevor Elliott on 20/11/2025.
//


import SwiftUI

struct SettingsView: View {
    var body: some View {
        NavigationStack {
            Form {
                Section("About This App") {
                    Text("FaithBuilder QuickView is a Bible study helper designed for Christian school students and teachers. It provides topic overviews, Scripture references, and AI-assisted answers to Bible questions.")
                        .font(.footnote)
                }
                
                Section("Doctrinal Framework") {
                    Text("""
This app uses the “Search for Truth” Bible study course as a doctrinal framework and teaching outline.

No pages, charts, or lesson content from the Search for Truth course are reproduced in this app. The material remains the copyrighted property of its original publisher. This app simply follows similar themes and the overall storyline of Scripture (Creation to Christ to the Church).
""")
                    .font(.footnote)
                }
                
                Section("Bible Text – KJV") {
                    Text("""
Scripture text shown in this app is from the King James Version (KJV), which is in the public domain.

Bible text is retrieved dynamically from a public Bible API (bible-api.com) and is used for study and devotional purposes only.
""")
                    .font(.footnote)
                }
                
                Section("AI Answers & Privacy") {
                    Text("""
AI answers are generated by an online language model based on the Bible and the doctrinal framework described above.

Please do not enter personal, private, or confidential information into questions. Sensitive issues should always be discussed with trusted adults and pastoral staff.
""")
                    .font(.footnote)
                }
                
                Section("Pastoral Care & Safety") {
                    Text("""
This app is not a counselling or crisis service.

If you are struggling with fear, anxiety, self-harm, abuse, or any serious emotional or spiritual issue, please speak directly with:
• A parent or guardian
• Your school chaplain or counsellor
• A trusted pastor or youth leader

You are not alone, and it is always okay to ask for help.
""")
                    .font(.footnote)
                }
            }
            .navigationTitle("About & Licensing")
        }
    }
}
